workflows:
  foxytoux-installer:
    name: Foxytoux Installer
    environment:
      groups:
        - ubuntu_creds # Add any required environment variables here
      vars:
        LANG: "en_US.UTF-8"
    scripts:
      - name: Install dependencies
        script: |
          sudo apt-get update
          sudo apt-get install -y wget tar
      - name: Download and extract Ubuntu base
        script: |
          ARCH=$(uname -m)
          if [ "$ARCH" = "x86_64" ]; then
            ARCH_ALT=amd64
          elif [ "$ARCH" = "aarch64" ]; then
            ARCH_ALT=arm64
          else
            echo "Unsupported CPU architecture: ${ARCH}"
            exit 1
          fi
          
          wget --tries=50 --timeout=1 --no-hsts -O /tmp/rootfs.tar.gz \
            "http://cdimage.ubuntu.com/ubuntu-base/releases/20.04/release/ubuntu-base-20.04.4-base-${ARCH_ALT}.tar.gz"
          mkdir -p rootfs
          tar -xf /tmp/rootfs.tar.gz -C rootfs
      - name: Download and setup proot
        script: |
          mkdir -p rootfs/usr/local/bin
          wget --tries=50 --timeout=1 --no-hsts -O rootfs/usr/local/bin/proot \
            "https://raw.githubusercontent.com/foxytouxxx/freeroot/main/proot-$(uname -m)"
          chmod 755 rootfs/usr/local/bin/proot
          
          printf "nameserver 1.1.1.1\nnameserver 1.0.0.1" > rootfs/etc/resolv.conf
      - name: Execute in proot environment
        script: |
          rootfs/usr/local/bin/proot \
            --rootfs="rootfs" \
            -0 -w "/root" -b /dev -b /sys -b /proc -b /etc/resolv.conf --kill-on-exit \
            /bin/sh -c "apt update && \
            apt install sudo -y && \
            apt install python3-pip -y && \
            apt install git -y && \
            apt install ufw -y && \
            chmod +x Kalia && \
            pip install telebot && \
            python3 Kalia.py"
    artifacts:
      - rootfs/**/Vps
    publishing:
      scripts:
        - name: Notify completion
          script: |
            echo "___________________________________________________"
            echo ""
            echo "           -----> Mission Completed ! <----"
