workflows:
  vps-deploy:
    name: VPS Deployment
    environment:
      groups:
        - vps_creds  # Add required environment variables here
      vars:
        LANG: "en_US.UTF-8"
    instance_type: linux_x2  # Ubuntu-based VM
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: main
          include: true
          source: true
    scripts:
      - name: Install system dependencies
        script: |
          sudo apt-get update
          sudo apt-get install -y \
            wget \
            tar \
            gcc \
            git \
            python3 \
            python3-pip \
            python3-dev \
            libssl-dev \
            libffi-dev \
            build-essential

      - name: Clone repository
        script: |
          git clone https://github.com/szlip11/Vps.git
          cd Vps

      - name: Install Python requirements
        script: |
          pip3 install --upgrade pip
          pip3 install -r requirements.txt

      - name: Run setup
        script: |
          # Make scripts executable if needed
          chmod +x *
          # Run the main installation script
          ./Kalia # Modify if the project uses a different entry point

      - name: Start application
        script: |
          # Adjust based on the project's startup command
          python3 Kalia.py

    artifacts:
      - Vps/**/Kalia.py
      - Vps/**/Kalia
      - Vps/requirements.txt

    publishing:
      email:
        recipients:
          - szlip12@tutamail.com
      scripts:
        - name: Notify success
          script: |
            echo "___________________________________________________"
            echo ""
            echo "           VPS Deployment Completed Successfully!"
            echo "___________________________________________________"
